services:
  healthchecker:
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      args:
        - GO_VERSION=1.19
        - MIGRATE_VERSION=4.15.2
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:8080 | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    volumes:
      - logstashdata:/usr/share/logstash/data

  kibana:
    volumes:
      - kibanadata:/usr/share/kibana/data

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
  logstashdata:
    driver: local
  kibanadata:
    driver: local
