wipe = true

[psql]
blacklist = ["schema_migrations"]

dbname = "elasticsearch-capable-web-app_db"
host   = "localhost"
port   = 5432
user   = "elasticsearch-capable-web-app"
pass   = "elasticsearch-capable-web-app_secrets"
sslmode = "disable"