wipe = true

[aliases.tables.posts.relationships.posts_contributed_by_fk_users]
local = "ContributedPosts"
foreign = "ContributingUser"

[psql]
blacklist = ["schema_migrations"]

dbname = "elasticsearch-capable-web-app_db"
host   = "localhost"
port   = 5432
user   = "elasticsearch-capable-web-app"
pass   = "elasticsearch-capable-web-app_secrets"
sslmode = "disable"