// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Posts      string
	PostsAudit string
	Users      string
}{
	Posts:      "posts",
	PostsAudit: "posts_audit",
	Users:      "users",
}
